# Imports

In [1]:
from pathlib import Path

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

# Datas

ورودی از `data/processed` خوانده می شه و خروجی های آماده ساخت دیتابیس در `data/database` ذخیره می شن.

In [2]:
project_root = Path.cwd()
if not (project_root / "data" / "processed").is_dir():
    project_root = project_root.parent

input_dir = project_root / "data" / "processed"
output_dir = project_root / "data" / "database"

players = pd.read_csv(input_dir / "players.csv")
team_rosters = pd.read_csv(input_dir / "team_rosters.csv")
mvp_votes = pd.read_csv(input_dir / "mvp_votes.csv")
player_season = pd.read_csv(input_dir / "player_seasons.csv")
champions = pd.read_csv(input_dir / "champions.csv")

# team

In [3]:
df_player_season = player_season.copy()
teams = df_player_season['team_label'].unique().dropna()
teams = np.sort(teams)
lst= []
for i in range(len(teams)):
    lst.append(i+1)
df_team = pd.DataFrame({
    'team_id': lst,
    'team_label': teams
})
df_team

    team_id team_label
0         1        2TM
1         2        3TM
2         3        4TM
3         4        ATL
4         5        BOS
5         6        BRK
6         7        CHI
7         8        CHO
8         9        CLE
9        10        DAL
10       11        DEN
11       12        DET
12       13        GSW
13       14        HOU
14       15        IND
15       16        LAC
16       17        LAL
17       18        MEM
18       19        MIA
19       20        MIL
20       21        MIN
21       22        NOP
22       23        NYK
23       24        OKC
24       25        ORL
25       26        PHI
26       27        PHO
27       28        POR
28       29        SAC
29       30        SAS
30       31        TOR
31       32        UTA
32       33        WAS

# Champion

In [4]:
champions.head(10)

,season,team_id,team_name,source_url,fetched_at
0,2020,LAL,Los Angeles Lakers,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00
1,2021,MIL,Milwaukee Bucks,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00
2,2022,GSW,Golden State Warriors,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00
3,2023,DEN,Denver Nuggets,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00
4,2024,BOS,Boston Celtics,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00
5,2025,OKC,Oklahoma City Thunder,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00
6,2026,NYK,New York Knicks,https://www.basketball-reference.com/leagues/,2026-10-19T04:00:44.407561+00:00

In [5]:
df_champ = champions.copy()
seasons = df_champ['season'].unique()

for i, seas in enumerate(seasons, start=1):
    df_champ['season'] = df_champ['season'].replace(seas, i)
df_champ = df_champ.rename(columns= {'season': 'season_id'})
df_champ['team_id'] = df_champ['team_id'].map(df_team.set_index('team_label')['team_id'])

df_champ = df_champ[['season_id','team_id']]
df_champ

   season_id  team_id
0          1       17
1          2       20
2          3       13
3          4       11
4          5        5
5          6       24
6          7       23

# Season

In [6]:
df_season = champions.copy()
df_season['season_id'] = df_champ['season_id']
df_season = df_season[['season_id','season']]
df_season

   season_id  season
0          1    2020
1          2    2021
2          3    2022
3          4    2023
4          5    2024
5          6    2025
6          7    2026

# Positions

In [7]:
team_rosters.head(10)

,season,team_id,player_id,position,age,experience_years,height_cm,weight_kg,source_url,fetched_at,age_source_url,age_fetched_at
0,2020,ATL,bembrde01,SG,25.0,3,195.58,95.25,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
1,2020,ATL,brownch02,SG,22.0,0,198.12,90.26,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
2,2020,ATL,cartevi01,PF,43.0,21,198.12,99.79,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
3,2020,ATL,collijo01,PF,22.0,2,205.74,102.51,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
4,2020,ATL,crabbal01,SG,27.0,6,195.58,96.16,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
5,2020,ATL,dedmode01,C,30.0,6,208.28,111.13,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
6,2020,ATL,fernabr01,C,21.0,0,205.74,108.86,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
7,2020,ATL,goodwbr01,PG,24.0,1,182.88,81.65,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
8,2020,ATL,grahatr01,SF,26.0,3,195.58,99.34,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00
9,2020,ATL,huertke01,SG,21.0,1,198.12,86.18,https://www.basketball-reference.com/teams/ATL...,2026-10-19T04:00:48.447337+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00

In [8]:

positions = team_rosters['position'].unique()
positions = np.sort(positions)
lst_pose=[1,2,3,4,5]
df_positions = pd.DataFrame({
        'position_id':lst_pose,
    'position' : positions
})
df_positions

   position_id position
0            1        C
1            2       PF
2            3       PG
3            4       SF
4            5       SG

# Experience

In [9]:
df_experience = team_rosters.copy()
df_experience = df_experience.rename(columns= {'position': 'position_id'})
df_experience = df_experience.rename(columns= {'season': 'season_id'})
df_experience['team_id'] = df_experience['team_id'].map(df_team.set_index('team_label')['team_id'])
df_experience['season_id'] = df_experience['season_id'].map(df_season.set_index('season')['season_id'])
df_experience['position_id'] = df_experience['position_id'].map(df_positions.set_index('position')['position_id'])
lst_exp= []
for i in range(len(df_experience['season_id'])):
    lst_exp.append(i+1)
df_experienced = pd.DataFrame({'experience_id' : lst_exp})
df_experience['experience_id'] = df_experienced['experience_id']
df_experience= df_experience[['experience_id','season_id','team_id','player_id','experience_years']]

# Players

In [10]:
players.head(10)

,player_id,name,birth_date,height_cm,weight_kg,birth_country,nationality,measurement_scope,source_url,fetched_at
0,achiupr01,Precious Achiuwa,1999-09-19,203.20,110.22,NG,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:01.724150+00:00
1,adamsja01,Jaylen Adams,1996-05-04,182.88,102.06,US,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:05.794448+00:00
2,adamsst01,Steven Adams,1993-07-20,210.82,120.20,NZ,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:09.813028+00:00
3,adebaba01,Bam Adebayo,1997-07-18,205.74,117.93,US,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:13.729921+00:00
4,agbajoc01,Ochai Agbaji,2000-04-20,195.58,97.52,US,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:17.716766+00:00
5,aldamsa01,Santi Aldama,2001-01-10,213.36,97.52,ES,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:21.844293+00:00
6,aldrila01,LaMarcus Aldridge,1985-07-19,210.82,113.40,US,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:25.828404+00:00
7,alexaky01,Kyle Alexander,1996-10-21,210.82,99.79,CA,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:29.703253+00:00
8,alexani01,Nickeil Alexander-Walker,1998-09-02,195.58,92.99,CA,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:33.751612+00:00
9,alexatr01,Trey Alexander,2003-05-02,195.58,83.91,US,NaN,profile_snapshot,https://www.basketball-reference.com/players/a...,2026-10-19T04:16:37.831250+00:00

In [11]:
df_player = players.copy()
df_player = df_player[['player_id','name','birth_date','height_cm','weight_kg','birth_country']]

# MVP_Votes

In [12]:
mvp_votes.head(10)

,season,player_id,rank,first_place_votes,points_won,points_max,vote_share,source_url,fetched_at
0,2020,antetgi01,1,85,962.0,1010.0,0.952,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
1,2020,jamesle01,2,16,753.0,1010.0,0.746,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
2,2020,hardeja01,3,0,367.0,1010.0,0.363,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
3,2020,doncilu01,4,0,200.0,1010.0,0.198,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
4,2020,leonaka01,5,0,168.0,1010.0,0.166,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
5,2020,davisan02,6,0,82.0,1010.0,0.081,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
6,2020,paulch01,7,0,26.0,1010.0,0.026,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
7,2020,lillada01,8,0,23.0,1010.0,0.023,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
8,2020,jokicni01,9,0,18.0,1010.0,0.018,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00
9,2020,siakapa01,10,0,17.0,1010.0,0.017,https://www.basketball-reference.com/awards/aw...,2026-10-19T04:00:40.458009+00:00

In [13]:
df_mvp = mvp_votes.copy()
df_mvp = df_mvp.rename(columns= {'season': 'season_id'})
df_mvp['season_id'] = df_mvp['season_id'].map(df_season.set_index('season')['season_id'])
lst_mvp =[]
for i in range(len(df_mvp['season_id'])):
    lst_mvp.append(i +1)
df_mv = pd.DataFrame({'mvp_id': lst_mvp})
df_mvp['mvp_id'] =df_mv['mvp_id']
df_mvp = df_mvp[['mvp_id','season_id','player_id','rank','first_place_votes','points_won','points_max','vote_share']]
df_mvp

,mvp_id,season_id,player_id,rank,first_place_votes,points_won,points_max,vote_share
0,1,1,antetgi01,1,85,962.0,1010.0,0.952
1,2,1,jamesle01,2,16,753.0,1010.0,0.746
2,3,1,hardeja01,3,0,367.0,1010.0,0.363
3,4,1,doncilu01,4,0,200.0,1010.0,0.198
4,5,1,leonaka01,5,0,168.0,1010.0,0.166
...,...,...,...,...,...,...,...,...
76,77,7,doncilu01,4,0,250.0,1000.0,0.250
77,78,7,cunnica01,5,2,117.0,1000.0,0.117
78,79,7,brownja02,6,0,89.0,1000.0,0.089
79,80,7,leonaka01,7,0,1.0,1000.0,0.001
80,81,7,mitchdo01,7,0,1.0,1000.0,0.001

# Player 0f seasons

In [14]:
player_season.head(10)

,season,player_id,team_id,team_label,is_total,age,position,games,games_started,minutes_per_game,...,true_shooting_pct,usage_pct,ws,ws_per_48,bpm,vorp,source_url,fetched_at,advanced_source_url,advanced_fetched_at
0,2020,hardeja01,HOU,HOU,False,30,SG,68,68,36.5,...,0.626,36.3,13.1,0.254,9.6,7.3,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
1,2020,bealbr01,WAS,WAS,False,26,SG,57,57,36.0,...,0.579,34.4,5.1,0.118,2.9,2.5,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
2,2020,lillada01,POR,POR,False,29,PG,66,66,37.5,...,0.627,30.3,11.6,0.225,7.5,5.9,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
3,2020,youngtr01,ATL,ATL,False,21,PG,60,60,35.3,...,0.595,34.9,5.9,0.133,3.9,3.1,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
4,2020,antetgi01,MIL,MIL,False,25,PF,63,63,30.4,...,0.613,37.5,11.1,0.279,11.5,6.6,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
5,2020,doncilu01,DAL,DAL,False,20,PG,61,61,33.6,...,0.585,36.8,8.8,0.207,8.4,5.4,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
6,2020,irvinky01,BRK,BRK,False,27,PG,20,20,32.9,...,0.595,32.6,2.9,0.210,7.7,1.6,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
7,2020,westbru01,HOU,HOU,False,31,PG,57,57,35.9,...,0.536,34.4,4.2,0.098,1.5,1.8,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
8,2020,leonaka01,LAC,LAC,False,28,SF,57,57,32.4,...,0.589,33.0,8.7,0.226,8.9,5.1,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00
9,2020,bookede01,PHO,PHO,False,23,SG,70,70,35.9,...,0.618,30.0,7.5,0.143,2.2,2.6,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:33.165931+00:00,https://www.basketball-reference.com/leagues/N...,2026-10-19T04:00:36.626392+00:00

In [15]:
df_player_season = df_player_season.rename(columns= {'position': 'position_id'})
df_player_season = df_player_season.rename(columns= {'season': 'season_id'})
df_player_season['team_id'] = df_player_season['team_label'].map(df_team.set_index('team_label')['team_id'])
df_player_season['season_id'] = df_player_season['season_id'].map(df_season.set_index('season')['season_id'])
df_player_season['position_id'] = df_player_season['position_id'].map(df_positions.set_index('position')['position_id'])
df_player_season['is_total'] = df_player_season['is_total'].map({False : 0, True : 1})
lst_play = []
for i in range(len(df_player_season['season_id'])):
    lst_play.append(i + 1)
df_player_season.insert(0, 'player_season_id', lst_play)
df_player_season = df_player_season.drop(
    ['team_label', 'source_url', 'fetched_at', 'advanced_source_url', 'advanced_fetched_at'],
    axis=1
)

df_player_season

,player_season_id,season_id,player_id,team_id,is_total,age,position_id,games,games_started,minutes_per_game,...,turnovers_per_game,personal_fouls_per_game,points_per_game,per,true_shooting_pct,usage_pct,ws,ws_per_48,bpm,vorp
0,1,1,hardeja01,14,0,30,5,68,68,36.5,...,4.5,3.3,34.3,29.1,0.626,36.3,13.1,0.254,9.6,7.3
1,2,1,bealbr01,33,0,26,5,57,57,36.0,...,3.4,2.2,30.5,23.2,0.579,34.4,5.1,0.118,2.9,2.5
2,3,1,lillada01,28,0,29,3,66,66,37.5,...,2.9,1.7,30.0,26.9,0.627,30.3,11.6,0.225,7.5,5.9
3,4,1,youngtr01,4,0,21,3,60,60,35.3,...,4.8,1.7,29.6,23.9,0.595,34.9,5.9,0.133,3.9,3.1
4,5,1,antetgi01,20,0,25,2,63,63,30.4,...,3.7,3.1,29.5,31.9,0.613,37.5,11.1,0.279,11.5,6.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,5046,7,telfoja01,16,0,24,2,8,0,4.0,...,0.1,0.6,0.1,-5.3,0.087,9.4,-0.1,-0.163,-13.8,-0.1
5046,5047,7,brownda04,9,0,26,5,1,0,3.0,...,0.0,0.0,0.0,-7.7,0.000,14.0,0.0,-0.269,-18.7,0.0
5047,5048,7,essenno01,7,0,19,2,2,0,3.0,...,0.0,0.5,0.0,-11.9,0.000,20.8,-0.1,-0.417,-23.7,0.0
5048,5049,7,evbuoto01,23,0,24,4,5,0,1.6,...,0.0,0.2,0.0,-0.3,0.000,5.4,0.0,-0.025,-11.5,0.0
5049,5050,7,hepbuch01,31,0,22,3,2,0,6.5,...,0.5,1.0,0.0,-13.5,0.000,23.1,-0.1,-0.441,-23.8,-0.1

# New Datas

In [16]:
output_dir.mkdir(parents=True, exist_ok=True)

df_player_season.to_csv(output_dir / "player_season.csv", index=False)
df_mvp.to_csv(output_dir / "mvp_votes.csv", index=False)
df_experience.to_csv(output_dir / "experience.csv", index=False)
df_season.to_csv(output_dir / "seasons.csv", index=False)
df_positions.to_csv(output_dir / "positions.csv", index=False)
df_player.to_csv(output_dir / "players.csv", index=False)
df_champ.to_csv(output_dir / "champions.csv", index=False)
df_team.to_csv(output_dir / "team.csv", index=False)